### ISSUE TITLE
The variable has never been declared or initialized anywhere, Recaptcha does not work

### ISSUE THREAD

**Issue by chumachkin** [rocketgeek/wp-members-dev#1]
https://github.com/rocketgeek/wp-members-dev/blob/6fa96e8893b8e167d32b2f7144b305b28089334f/includes/class-wp-members-captcha.php#L193

**Comment by rocketgeek** [comment]
This issue affects reCAPTCHA v2 making it seem that the captcha was never checked.  It was corrected in the production release of the plugin 3.3.2.2.  Unfortunately, while it appears that it was fixed in the development packages, that apparently was not pushed up to this repo.  It has been pushed now (although it was inadvertently included in [an unrelated commit](https://github.com/rocketgeek/wp-members-dev/commit/adf09b079ffb995d9e520dd9533dd14780154d96), which might be why it wasn't pushed ealier).
